#!/bin/bash

# глобальные переменные
version="0.0.0"

# цвета
green="\e[1;32m"
red="\e[1;31m"
reset="\e[1;0m"

# функции
function hp {
        echo -e "$green-jutsu2mp4-$reset v$version\n"
        echo -e "$greenиспользование:$reset jutsu2mp4 -опция / --опции"
        echo "все опции:"
        echo ""
        echo -e "$green-h$reset / $green--help$reset: показать это сообщение" 
        echo -e "$green-d$reset / $green--download$reset: сгенерировать ссылку на скачивание эпизода"
        echo -e "$green-s$reset / $green--status$reset: проверить статус jut.su"
        echo ""
        echo "если вы хотите сообщить о ошибке связанной с скриптом, можете сделать это здесь: https://github.com/meth1337/jutsu2mp4-linux/issues"
}

function st {
        echo "вы можете остановить процесс с помощью ctrl+c."
        echo ""
        ping jut.su
}

function dl {
        echo -e "$greenвведите ссылку на эпизод$reset: "
        read url
        webdrivers/webdriver-invisible $url
        clear
        echo -e "$greenссылки на скачивание$reset:"
        cat tmp.html | src/pup "video" | tail -n +2 | head -4
        rm tmp.html
        rm geckodriver.log
}

# работа с аргументами
case "${1}" in
        -h|--help)
                hp
                ;;
        -s|--status)
                st
                ;;
        -d|--download)
                dl
                ;;
        -?*)
                echo -e "$redошибка$reset: неизвестная опция: $1"
                echo "чтобы получить возможные опции используйте $0 -h"
        #*)
        #    echo "$redошибка$reset: вы не указали опцию!"
        #       echo "чтобы получить список опций используйте $0 -h"
        #       ;;
esac

